-- This script drops all tables, custom types, and the schema itself.
-- It's useful for a complete teardown of the database structure.

DROP TABLE IF EXISTS dbo.PLAYER_HAND CASCADE;
DROP TABLE IF EXISTS dbo.ROUND CASCADE;
DROP TABLE IF EXISTS dbo.GAME_PLAYER CASCADE;
DROP TABLE IF EXISTS dbo.GAME CASCADE;
DROP TABLE IF EXISTS dbo.LOBBY_PLAYER CASCADE;
DROP TABLE IF EXISTS dbo.LOBBY CASCADE;
DROP TABLE IF EXISTS dbo.TOKEN CASCADE;
DROP TABLE IF EXISTS dbo.USERS CASCADE;

DROP TYPE IF EXISTS dbo.GAME_STATE;

DROP SCHEMA IF EXISTS dbo CASCADE;
