### Admin Login
POST http://localhost:8080/api/users/token
Content-Type: application/json

{
  "email": "Admin@gmail.com",
  "password": "password123"
}

### Generate Invite for new user
POST http://localhost:8080/api/users/invite
Authorization: Bearer tcYYBpWTgWVDAmfJtyxufuva25m9-07Ai0oglbbbbZc=

### Create New First User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "jaco",
  "email": "jaco@gmail.com",
  "password": "jaco",
  "invite": "nw8vtcoGT7AWEkmt-O2htw=="
}

### Create New Second User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "player1",
  "email": "player1@gmail.com",
  "password": "player1",
  "invite": "Wz4klZSMTX2wxWOeg6gP-Q=="
}

### Get token of first user
POST http://localhost:8080/api/users/token
Content-Type: application/json

{
  "email": "jaco@gmail.com",
  "password": "jaco"
}

### Get token of second user
POST http://localhost:8080/api/users/token
Content-Type: application/json

{
  "email": "player1@gmail.com",
  "password": "player1"
}

### Create Lobby with First User (host)
POST http://localhost:8080/api/lobbies
Authorization: Bearer 7ICF6NzpmSp2YL9b-wGWPudqT7c3soG4P6z5Hqpd2zE=
Content-Type: application/json

{
  "name": "host lobby",
  "description": "lobby for presentation",
  "maxPlayers": 6,
  "minPlayers": 2
}

### Join Lobby with Second User (player1)
POST http://localhost:8080/api/lobbies/1/join
Authorization: Bearer Nwbxo0x96pW3aBxJnWhTy_-aGnt_jDDcn0KZW9XVmIM=

### Create Game with host permission
POST http://localhost:8080/api/games
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=
Content-Type: application/json

{
  "lobbyId": 1,
  "numberOfRounds": 2
}

### Start Game with host permission
POST http://localhost:8080/api/games/1/start
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### Start new round
POST http://localhost:8080/api/games/1/rounds/start
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### First player of the rounds sets ante
POST http://localhost:8080/api/games/1/rounds/ante
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=
Content-Type: application/json

{
  "ante": 25
}

### Everyone pays the ante
POST http://localhost:8080/api/games/1/rounds/pay-ante
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=
Content-Type: application/json

### Roll dices
POST http://localhost:8080/api/games/1/rounds/roll-dices
Authorization: Bearer gkyiT2FNA2J5-iWcAtrqmYtfpPrA0_Fqxmag9KiZmxg=

### Choose which dices to keep
POST http://localhost:8080/api/games/1/rounds/update-turn
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=
Content-Type: application/json

{
  "dice": "9"
}

### Move on to next player's turn
POST http://localhost:8080/api/games/1/rounds/next-turn
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=

### Roll dices
POST http://localhost:8080/api/games/1/rounds/roll-dices
Authorization: Bearer s0aP2jtgKkWUczI4W0Ha894_xQP-r1cGItTBzGK5p-E=

### Choose which dices to keep
POST http://localhost:8080/api/games/1/rounds/update-turn
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=
Content-Type: application/json

{
  "dice": "A"
}

### Check Winner of the round
POST http://localhost:8080/api/games/1/rounds/check-round-winner
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=

### Distribute Winnings
POST http://localhost:8080/api/games/1/rounds/distribute-winnings
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=

### Start second Round
POST http://localhost:8080/api/games/1/rounds/start
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=

### First player of the rounds sets ante
POST http://localhost:8080/api/games/1/rounds/ante
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=
Content-Type: application/json

{
  "ante": 50
}

### Everyone pays the ante
POST http://localhost:8080/api/games/1/rounds/pay-ante
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=
Content-Type: application/json

### Roll dices
POST http://localhost:8080/api/games/1/rounds/roll-dices
Authorization: Bearer gkyiT2FNA2J5-iWcAtrqmYtfpPrA0_Fqxmag9KiZmxg=

### Choose which dices to keep
POST http://localhost:8080/api/games/1/rounds/update-turn
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=
Content-Type: application/json

{
  "dice": "9"
}

### Move on to next player's turn
POST http://localhost:8080/api/games/1/rounds/next-turn
Authorization: Bearer lt06gxKC2MhFTvDznyFcVIu3c1jZbNqDd9ROAcLGD7g=

### Roll dices
POST http://localhost:8080/api/games/6/rounds/roll-dices
Authorization: Bearer fyRrCiQtTpmZgwwQZ-rFKyk55cEGd54fRFUOMJotPjg=

### Choose which dices to keep
POST http://localhost:8080/api/games/1/rounds/update-turn
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=
Content-Type: application/json

{
  "dice": "A"
}

### Check Winner of the final round
POST http://localhost:8080/api/games/1/rounds/check-round-winner
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### Distribute Winnings
POST http://localhost:8080/api/games/1/rounds/distribute-winnings
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### End game
POST http://localhost:8080/api/games/1/end
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### Check winner of the game
POST http://localhost:8080/api/games/1/check-game-winner
Authorization: Bearer nTmseDm7o5yf30wSlbHIoziWVWLolo7H--M35CkUK5E=

### Listen
GET http://localhost:8080/api/lobbies/listen
Authorization: Bearer b9RTD7N95yjq7QF19pXXfPv8qcAxA46JvxOtgjTlSUI=
