FROM node:22 AS builder

WORKDIR /app

COPY ts/package*.json ./

RUN npm install

COPY ts/ .

RUN npm run build

FROM nginx

COPY ts/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
