FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copy the unpacked JAR dependencies
COPY app/build/dependency/BOOT-INF/lib /app/lib
COPY app/build/dependency/META-INF /app/META-INF
COPY app/build/dependency/BOOT-INF/classes /app

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-cp", "/app:/app/lib/*", "org.example.AppKt"]

